# Generated by Django 5.1.1 on 2024-10-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='category/')),
                ('category_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=1000)),
                ('care_instructions', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('product_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_price', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='product_image/')),
                ('productItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productitem')),
            ],
        ),
        migrations.AddField(
            model_name='productcategory',
            name='size_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sizecategory'),
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('sizeId', models.AutoField(primary_key=True, serialize=False)),
                ('size_name', models.CharField(max_length=100)),
                ('sort_order', models.CharField(max_length=100)),
                ('size_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sizecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariaation',
            fields=[
                ('VariationId', models.AutoField(primary_key=True, serialize=False)),
                ('qty_in_stock', models.IntegerField()),
                ('ProductItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productitem')),
                ('sizeOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sizeoption')),
            ],
        ),
    ]
