# Generated by Django 5.1.1 on 2024-10-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_color_productcategory_sizecategory_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariaation',
            new_name='ProductVariation',
        ),
    ]
