# Generated by Django 5.1.1 on 2024-10-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_productvariaation_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
