# Generated by Django 5.1.1 on 2024-10-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productitem_image1_productitem_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
