# Generated by Django 5.1.1 on 2024-10-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_coupon_alter_orderitem_size_payment_order_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orderitem'),
        ),
    ]
